### ISSUE TITLE
User can vote for more than one candidate

### ISSUE THREAD

**Issue by Strick9ers** [BreslinRy/Web-Voting-Application#1]
Bug Classification: defect
	Bug Location: GUI.py
	Bug Priority: 3
	How to reproduce:
		1.  User Selects both candidates
		2.  User submits vote
  Expected Result:
    Clears users previous input when another candidate is selected.
  Actual Result: 
	  Saves users vote as one for each candidate.

**Comment by BreslinRy** [comment]
Fixed in the new version using radio buttons
