### ISSUE TITLE
Exiting the gui before submitting counts the votes

### ISSUE THREAD

**Issue by Strick9ers** [BreslinRy/Web-Voting-Application#3]
Bug Classification: defect
	Bug Location: GUI.py
	Bug Priority: 2
	How to reproduce:
		1. User selects a candidate to vote for
		2. User exits the program without submitting vote 
  Expected Result:
    Users session is voided and vote is not counted
  Actual Result: 
	  Vote is counted

**Comment by BreslinRy** [comment]
The implementation of radiobuttons along with changing the way count worked fixed this
