### ISSUE TITLE
Count Function can count more or less than one vote per session

### ISSUE THREAD

**Issue by Strick9ers** [BreslinRy/Web-Voting-Application#4]
Bug Classification: enhancement
	Bug Location: count.py
	Bug Priority: 4
	How to reproduce:
		1. Any number other than one or zero is used as a parameter to count function
  Expected Result:
    Count function increments by one if vote was passed for a certain user
  Actual Result: 
	  Count function adds the number that was inserted as a parameter to count to the existing data.

**Comment by BreslinRy** [comment]
As the count function does not work this way anymore this issue no longer exists.
